.github/CODEOWNERS, serverless/README.md
Updates to the readme for grammar, style and documentation site optimization
Expanded docs!
=> updates to the readme to prep it for being pulled into the documentation

serverless/package.json, serverless/src/index.ts, serverless/src/tags.ts, serverless/template.yml, serverless/test/index.spec.ts, serverless/test/tags.spec.ts
With this change we tag the lambda functions built with the macro with the version used. This will allow us to get some usage tracking and help debug issues.
This change is part of the telemetry/usage OKR
- Unit tests
- Manual changes using SAM.
- [] Misc (docs, refactoring, dependency upgrade, etc.)
=> Tag Lambda functions with macro version

serverless/README.md
Adds instructions on how to upgrade/install a specific macro version.
=> Add instructions on upgrading the macro to specific versions

serverless/src/layer.ts, serverless/test/env.spec.ts, serverless/test/layer.spec.ts, serverless/test/tracing.spec.ts
Fix formatting issues.
Failing formatter check.
No functional changes.
=> Fix formatting issues

serverless/README.md
Add docs site front matter
Front matter should live with the docs
N/A
https://github.com/DataDog/documentation/pull/12788
=> DOCS-2583 Add docs site front matter

serverless/README.md
=> Cover missing permission case in troubleshooting guide.

serverless/tools/create_test_stack.sh, serverless/tools/installation_test.sh, serverless/tools/update_test_stack.sh
Update the staging s3 bucket used in our test script
New bucket
Deployed a test stack
=> Update staging s3 bucket used in test script

serverless/src/layer.ts, serverless/test/layer.spec.ts
=> feat: Support python 310

serverless/template.yml
Closes #101 
I deployed a test version manually:
And verified it properly instrumented my test stack. You can see the python function metrics were all successful, so I have a decent amount of confidence in this:
=> feat: Bump python to 3.11

.github/workflows/build_serverless.yml, serverless/template.yml
Upgrades the runtime in `template.yml`
#120 
GH Checks
Also removed Node.js 16 from some workflows.
=> feat: set template to `nodejs20.x`

serverless/yarn.lock
Upgrades dependencies
Vulnerability fixes
n/a
`yarn upgrade`
=> chore: upgrade dependencies

serverless/release.sh
=> feat: remove hub

serverless/src/step_function/span-link.ts, serverless/test/step_function/span-link.spec.ts
Set up "Step Function -> Lambda" trace merging, i.e. modifies Lambda invocation step's payload so that at execution time, some context of the Step Function will be passed to the Lambda function, which will be used to merge traces and link spans.
=> [Step Function] 7.4 Set up SFN->Lambda trace merging

serverless/src/step_function/span-link.ts, serverless/test/step_function/span-link.spec.ts
Set up "Step Function -> Step Function" trace merging, i.e. modifies Step Function invocation step's payload so that at execution time, some context of the outer Step Function will be passed to the nested Step Function, which will be used to merge traces and link spans.
=> [Step Function] 7.5 Set up SFN->SFN trace merging

serverless/Dockerfile
Adds a Docker file for gitlab ci 
See [PR](https://github.com/DataDog/datadog-cloudformation-macro/pull/170)
=> Add Docker file for ci

serverless/tools/get_secrets.sh
Adds a script that will retrieve secrets from the gitlab pipeline for automated release. Relevant PR. 
Tested locally
=> Add script to get secrets from gitlab ci 

serverless/Dockerfile
Updates the dockerfile to install yarn
=> [chore] update dockerfile to install yarn

serverless/release.sh
This PR fixes the path for template.yml when running the release script. Now that we're running release.sh from another repo, we get this error `grep: template.yml: No such file or directory`. This PR fixes the path of that file so we shouldn't run into those errors anymore. 
**Automated Testing - Running the gitlab pipeline**
I tested this by checking the results from the gitlab pipeline. You can see from the [results](https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/828957464) that the issue `grep: template.yml: No such file or directory` has been resolved.
=> [fix] fix the path for template.yml 

serverless/release.sh
Fixes the argument parsing for the release script
=> [chore] fix argument parsing for release script

serverless/Dockerfile
Installs node in the docker image
=> [chore] Install node

serverless/release.sh, serverless/tools/get_secrets.sh
This PR adds gh authentication to the release script so that we can run the subsequent `gh release` command.
=> Add github authentication in release script

serverless/src/layer.ts, serverless/test/layer.spec.ts
Support Python 3.13, referring to https://github.com/DataDog/datadog-cloudformation-macro/pull/115 (adding Python 3.12)
Customer request https://github.com/DataDog/datadog-cloudformation-macro/issues/188
Passed unit tests
=> feat: Support Python 3.13

.github/workflows/build_serverless.yml, serverless/package.json, serverless/release.sh, serverless/template.yml, serverless/yarn.lock
Upgrade the macro function to node22 since node18 is being deprecated this year, node is deprecating it end of April and AWS is deprecating it in September.
Also some minor changes to the release script to make it deployable from local so that the installation test script still works.
A customer asked about node18 being deprecated
* I ran the installation test script
* I used a test template with the following:
```
Transform:
- AWS::Serverless-2016-10-31
- Name: DatadogServerless
Parameters: 
nodeLayerVersion: 100
stackName: !Ref "AWS::StackName"
apiKey: 
extensionLayerVersion: 76
Resources:
HelloFunction:
Type: AWS::Serverless::Function
Properties:
CodeUri: ./
Handler: index.handler
Runtime: nodejs22.x
MemorySize: 512
Environment:
Variables:
DD_LAMBDA_HANDLER: index.handler
InlineCode: | …
```
=> Upgrade macro function to node22

serverless/release.sh
Since I uncommented the yarn test and there was no yarn install, the script cannot find jest.  This time to test it I ran the script except for the uploading parts, and it passes.
Error: https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/983387701#L103
The release process is broken
Ran the release script locally
=> Add yarn install

serverless/release.sh
This pr makes changes to the deployment script so variables are modified during a sandbox deploy. the template file will just work out of the box.
Not being able to use the template after a sandbox deploy was tedious this improves the experience.
I was able to verify the URL changing the parameter that is targeted. 
None!
=> [SVLS-6465] Adding template url to the url params
