DataDog/datadog-cloudformation-macro

serverless/README.md
serverless/release.sh
serverless/src/forwarder.ts
serverless/template.yml
serverless/test/forwarder.spec.ts
serverless/test/index.spec.ts
serverless/tools/create_test_stack.sh
serverless/tools/update_test_stack.sh

For customers who provide `forwarderArn`, create log groups and subscription filters through AWS SDK `createLogGroup` and `putSubscriptionFilter` instead of adding declarations to the CloudFormation template.
Currently, customers who are deploying their Lambdas for the first time will run into potential issues in later deployments. When the macro creates a log group and subscription filter by adding declarations to the template, this works fine the first time, but for later deployments, applying the macro again will result in those resources being deleted. This is because we currently have no way to determine which log groups were created by the macro. (If a log group was created by a macro in a previous iteration, we should add the declaration again to make sure it doesn't get removed.) …

Use AWS SDK to create log groups and subscription filters

---

CONTRIBUTING.md
serverless/README.md
serverless/template.yml

Add `PermissionsBoundaryArn` parameter support for `MacroFunctionZipCopier` function's roles
Small fixes in `README.md` file
All our roles should have permission boundaries
run local tests (yarn test) + deployed and tested `serverless/template.yaml` on our environment

PermissionsBoundaryArn for MacroFunctionZipCopier

---

serverless/README.md
serverless/src/env.ts
serverless/src/index.ts
serverless/src/layer.ts
serverless/test/index.spec.ts
serverless/test/layer.spec.ts

Adds the parameter of `isGovCloud` to have the GovCloud lambda layer be added to the user's functions.
SLS-701 - the GovCloud layer has a different ARN to be accounted for.
Added new unit tests to cover this case.

Adds option to use the GovCloud lambda layer

---

serverless/src/index.ts
serverless/src/tags.ts
serverless/test/index.spec.ts
serverless/test/tags.spec.ts

Adds a tag `lambda:createdBy` with the value `CDK` for lambdas that are provisioned with the AWS CDK. It follows the same tag key as `SAM`
Serverless telemetry
- Manually tested
- Unit tested

[serverless] Tag lambdas provisioned with CDK

---

serverless/package.json
serverless/src/index.ts
serverless/template.yml

Reverts #20, as it seems to cause the cloudformation macro to throw an error sometimes. We're still working on identifying when and why that error happens.

Revert datadog links

---

serverless/src/forwarder.ts
serverless/test/forwarder.spec.ts

This PR edits the logic in the forwarder.ts file to support two Cloudwatch log group subscription filters. Additionally this PR tests the new logic with unit tests in the forwarder.spec.ts file. This PR allows the Datadog Cloudformation macro to take full advantage of AWS cloudwatch log group's support for 2 log group subscription filters.
AWS Cloudwatch log groups added support for up to 2 subscription filters per log group and the Datadog Cloudformation macro logic currently only supports 1 subscription filter per log group.
I added unit tests for the new cases introduced by Cloudformations support of up to 2 log group subscription filters per log group and additionally manually tested these cases by repeatedly deploying a test SAM Lambda function with the test scenarios and confirming …

CloudFormation Macro support for two Cloudwatch log group subscription filters

---

README.md
serverless/src/layer.ts
serverless/test/layer.spec.ts

Add runtime to layer mapping for node 14
Allow using dd-trace in the new node 14 runtime without error: `Cannot find module 'dd-trace'`

Add runtime to layer mapping for node 14

---

serverless/src/env.ts
serverless/src/index.ts
serverless/src/layer.ts
serverless/test/env.spec.ts
serverless/test/index.spec.ts
serverless/test/layer.spec.ts

This PR adds support for the Datadog Lambda Extension via the CloudFormation Macro.
The team is making progress towards releasing the Datadog Lambda Extension for GA therefore we are putting in effort now to our existing integrations to add support for the Lambda Extension.
I manually deployed the CloudFormation stack to sandbox and used it in a sample SAM and CDK deployment. The Datadog Extension was added as a layer and did not break any of the existing layer adding logic.
I added a few local tests for the code changes I added.

Support for Datadog Lambda Extension

---

serverless/README.md
serverless/src/env.ts
serverless/test/env.spec.ts

Sets DD_SERVERLESS_LOGS_ENABLED environment variable (default: `true`) via `enableDDLogs` config

feature: Set DD_SERVERLESS_LOGS_ENABLED via enableDDLogs config

---

serverless/src/layer.ts
serverless/test/layer.spec.ts

- Add support for the Python 3.9 runtime
- Remove support for Node 8.10 runtime. This is not a breaking change because it has not been possible to update or create a Lambda function using this runtime since March 6, 2020.
- Remove region validation. The list of regions we validated against was out of date (it did not include `me-south-1`, `af-south-1`, or `eu-south-1`). It's difficult to keep this list up to date, and we don't do this type of validation in our other deployment tools.

Add support for Python 3.9, remove region validation

---

serverless/src/index.ts
serverless/src/layer.ts
serverless/test/env.spec.ts
serverless/test/layer.spec.ts
serverless/test/tracing.spec.ts

#48
I added support for Lambdas running on arm64 based architectures
The current macro adds the x86_64 layers to functions which caused our new arm based functions to fail
I added unit tests

feat: add support for arm64 lamdas

---

serverless/src/index.ts
serverless/src/layer.ts
serverless/test/layer.spec.ts

This PR allows to handle correctly runtime and architecture values if these values use Ref intrinsic function.
We needed to override findLambdas to handle our usage, this may be useful to others.
Tested by unit tests and deployments in our environments.
N/A

Add ref support to retrieve runtime & architecture in findLambdas

---

serverless/src/index.ts
serverless/src/tags.ts
serverless/test/index.spec.ts
serverless/test/tags.spec.ts

In a [previous PR](https://github.com/DataDog/datadog-cloudformation-macro/pull/63) to add DD_XXX env vars and tagging, I modified the tag formatting to be `{ [key: string]: string };` instead of `{ Key: string; Value: string }[];` but cloudformation requires the JSON object array for Tags so this PR reverts that change. 
Problem was reported [here](https://github.com/DataDog/datadog-cloudformation-macro/issues/64)
Updated all unit tests to what we now expect and everything seems to be passing and looking good

Revert Tag Formatting to JSON Object Arrays

---

serverless/src/tracing.ts
serverless/test/tracing.spec.ts

Right now, tracing is enabled globally without the ability to override on a function level, this PR aims to address that by setting the tracing config value only if the function doesn't have it defined on a local level. 
N/A
Deployed to our environment and it did what was intended which is not override tracing configs when we defined it on a function level.

fixing the override of trace config on a function level

---

serverless/README.md
serverless/src/env.ts
serverless/src/index.ts
serverless/test/env.spec.ts
serverless/test/tags.spec.ts

As discussed in #88, this adds the ability to specify configuration via environment variables on the Macro Lambda function.
Resolves #88
I wanted to simplify all of my SAM templates and not have each one specify the ARN of the Datadog secret, when it is the same in every region the Macro function is deployed.
The automated tests ensure the order of precedence for configuration is:
1. Default values
2. Environment variables specified on the Macro Lambda function
3. Mappings section or Parameters
... which allows the maximum flexibility.
One difference from the proposal in #88 is that I didn't have to modify any validation logic. I did this only by modifying the order in which configuration default values are read.
To be sure I didn't break anything in the tags code, I also added a test for …

Read config from ENV vars

---

serverless/README.md
serverless/src/env.ts
serverless/src/git.ts
serverless/test/git.spec.ts

Adds a param to the macro that can be used with SAM's --parameter-overrides option and local git commands to automatically add the `git.commit.sha` and `git.repository_url` tags used by Datadog Source Code Integration. 
Easy set up and usage of SCI
Deployed with a sample SAM app with and without setting the param.

Add Source Code Integration param and SAM usage instructions

---

serverless/src/index.ts
serverless/src/layer.ts
serverless/test/layer.spec.ts

Fixes a bug where the macro would get an error when the Layers definition was not an array, e.g. when it's a CFN conditional. This PR updates the code to handle this situation and add the expected layers to all possible outputs of the conditional
Bug
* Added unit tests
* Tested deploying a function with a conditional statement in its Layers definition

Handle conditionals in Layers definition

---

serverless/src/env.ts
serverless/test/env.spec.ts

* Fixes a bug where not all env vars would be set if the macro is used without the extension
* Fixes existing tests
* Adds unit tests
https://github.com/DataDog/datadog-cloudformation-macro/issues/92 thanks to @cscetbon
* Added unit tests
* Tested with an example stack

Fix env vars when macro is used without extensionLayerVersion set

---

serverless/template.yml

This increases the timeout necessary for the MacroFunction to process installing the Datadog Lambda layer to instrument Lambda functions.  
Default looks like it was 3 seconds and triggering a timeout and rollback which prevented deployment of our Stack.  
Manual regression
Related to issue with support team #1310259

Increases timeout for layer implementation

---

serverless/release.sh

Our release script won't work right now because we renamed the `master` branch to `main`, but the script still expects `master` to be the primary branch.
I'd like to release this library.

feat: Fix release script for renamed master to main

---

serverless/src/layer.ts
serverless/test/layer.spec.ts

Adds support for Python 3.12
We have [released](https://github.com/DataDog/datadog-lambda-python/releases/tag/v87) already the layers for this.
Updated a unit test.
n/a

feat: add `python3.12` support

---

.github/workflows/build_serverless.yml
serverless/package.json
serverless/release.sh
serverless/yarn.lock

Updates dependencies to not contain packages with vulnerabilities.
Also removes node 14 as a supported node version to build and test this macro.
#109 and #103 (this doesn't seem to be required, not updated automatically by the upgrade)
GitHub actions.
Next release is breaking for node14 users.

chore: upgrade dependencies

---

serverless/release.sh

Adds a dash character `-` to the release version in the launch script so future release tags are consistent with previous versions.
Release tag was created with a different pattern than that of previous versions
* https://github.com/DataDog/datadog-cloudformation-macro/tree/serverless-macro0.10.0
* https://github.com/DataDog/datadog-cloudformation-macro/tree/serverless-macro-0.9.0

Adds dash to release version in release script

---

serverless/src/index.ts
serverless/src/layer.ts
serverless/test/layer.spec.ts

Skip handling of container image Lambda functions. Lambda functions packaged into container images are instrumented with Datadog differently than Lambda functions packaged into a zip. The CloudFormation Macro should not make any changes to these container image Lambda functions.
https://github.com/DataDog/datadog-cloudformation-macro/issues/108
Created a SAM template with a zip Lambda function and container image Lambda function. Verified that (1) the zip Lambda function is instrumented with the CloudFormation Macro and sends metrics, logs, and traces to Datadog and (2) the container image Lambda function is unaffected by the CloudFormation Macro and sends metrics, logs, and traces to Datadog.
template.yaml
```
AWSTemplateFormatVersion: "2010-09-09"
Transform:
- AWS::Serverless-2016-10-31 …
```

Skip handling of container image lambda functions

---

serverless/src/layer.ts
serverless/test/layer.spec.ts

Adds support for .NET 8 runtime.
It has been widely available for AWS Lambda.
Added and updated tests.

feat: support `dotnet8` runtime

---

.github/workflows/build_serverless.yml
serverless/template.yml

Govcloud does not support node20 yet, so we gotta use node18 for now.

fix: revert node20, use node18 for govcloud

---

serverless/src/env.ts
serverless/src/index.ts
serverless/src/layer.ts
serverless/template.yml
serverless/test/env.spec.ts
serverless/test/index.spec.ts
serverless/test/layer.spec.ts

Currently there is no way to deploy with the cloudformation macro and only apply the extension. 
This PR adds this ability when the user sets `addLayers` to `false` the extension will still be applied.
To override this feature a new configuration option has been made called 'addExtension`.
This defaults to `true` ensuring the extension layer is applied. 
Currently if a customer is providing their own lambda libraries (dd-trace, datadog-lambda-js) there is no way to exclude these layers from the deployment and still retain the extension layer. This adds that functionality for this edge case.
In addition to the unit tests i used the release tool to upload my changes to a staging bucket that hosted the macro. Which i deployed to a sandbox aws environment and then created a new function using …

Allow the extension layer to be applied separately from the runtime layers

---

serverless/src/env.ts
serverless/src/index.ts
serverless/test/env.spec.ts
serverless/test/index.spec.ts

This pr sets the parameter `addExtension` to default to `false`.
Because this parameter requires additional parameters to operate. it can cause issues to existing workflows where the user might not intend to add the extension layer. 
This addresses #133 
Wrote tests that operate through the various configurations.

Setting addExtension to default to false

---

serverless/test/index.spec.ts
serverless/test/lambda/env.spec.ts
serverless/test/lambda/forwarder.spec.ts
serverless/test/lambda/git.spec.ts
serverless/test/lambda/lambda.spec.ts
serverless/test/lambda/layer.spec.ts
serverless/test/lambda/redirect.spec.ts
serverless/test/lambda/tags.spec.ts
serverless/test/lambda/tracing.spec.ts

Move tests node for Lambda to a `lambda` folder. Later I will create a `step_function` folder, so Lambda and Step Function code and tests will be separate and more clear.
Run `npm test` to run existing tests. They still pass.

Move lambda tests into a folder

---

serverless/src/index.ts
serverless/src/step_function/step_function.ts
serverless/src/step_function/types.ts
serverless/test/step_function/step_function.spec.ts

Sets up skeleton code for supporting step functions:
1. Add some basic step-function specific code in `step_function/step_function.ts`, including `instrumentStateMachines()`
2. Call `instrumentStateMachines()` in the main file `index.ts`
3. Add tests
To get ready to add step function instrumentation code.
1. Pass the added automated tests
2. Manually tested deploying the stacks, with some other changes. See …

[Step Function] 1. Set up skeleton code

---

.github/CODEOWNERS

Changing code owner from Serverless team to serverless-onboarding-enablement subteam
1. Onboarding and Enablement team is a more specific owner. 
2. Team members will be added as a reviewer in a Round Robin way.

Change code owner to ONE team

---

serverless/src/step_function/log.ts
serverless/test/step_function/log.spec.ts

Create a log group for the state machine if not already created.
This is one step of instrumenting a state machine.
1. Pass the added automated tests
2. Manually tested deploying the stacks, with some other changes. See https://github.com/DataDog/datadog-cloudformation-macro/pull/143. I decided to break that PR into smaller ones for easy review, and this PR is the first one.

[Step Function] 3. Create log group

---

serverless/src/index.ts
serverless/src/lambda/env.ts

Moves the code for getting Lambda config from `index.ts` to `lambda/env.ts`.
I'm going to add similar code (for getting config) for step functions. Putting it also in `index.ts`, as the Lambda code currently does, would make that file messy.
1. Pass the existing automated tests in `lambda/env.spec.ts`

[Step Function] 3.1 Refactor code for getting Lambda config

---

serverless/src/env.ts
serverless/src/index.ts
serverless/src/lambda/env.ts
serverless/test/lambda/env.spec.ts
serverless/test/lambda/tags.spec.ts

Moves some code for getting Lambda config from top-level functions into two classes:
- `ConfigLoader`, for common code for loading Lambda config and loading Step Function config
- `LambdaConfigLoader extends ConfigLoader`, for code specific to Lambda
To avoid duplicate code for loading Lambda config and for loading Step Function config. For example, …

[Step Function] 3.2 Extract class ConfigLoader and LambdaConfigLoader

---

serverless/src/index.ts
serverless/src/step_function/env.ts
serverless/src/step_function/step_function.ts
serverless/test/step_function/env.spec.ts

Instead of merging every PR into main branch, I'm going to merge them into a feature branch `yiming.luo/step-function` to avoid releasing partial support for step functions.
Similar to the existing class `LambdaConfigLoader` created in https://github.com/DataDog/datadog-cloudformation-macro/pull/150, this PR adds a class `StepFunctionConfigLoader`, which extends the same base class `ConfigLoader`.
To load step function config options set by the user, e.g. `env`.
1. Pass the added automated tests in `step_function/env.spec.ts`
1. In `env.spec.ts`, I can only use the `env` field, which is the only field for now. One …

[Step Function] 3.3. Add class StepFunctionConfigLoader

---

serverless/src/step_function/log.ts
serverless/src/step_function/step_function.ts
serverless/test/step_function/log.spec.ts

Instead of merging every PR into main branch, I'm going to merge them into a feature branch `yiming.luo/step-function` to avoid releasing partial support for step functions.
Pass the `env` field set in step function config to log group name, so the created log group name can be like `/aws/vendedlogs/states/MyStateMachine-Logs-dev`
We want env field to be part of log group name.
1. Pass the added automated tests in `step_function/log.spec.ts`

[Step Function] 3.4 Pass env from config to log group name

---

serverless/src/step_function/log.ts
serverless/test/step_function/log.spec.ts

Add permissions to the state machine role to allow it to log to CloudWatch Logs.
This is one step of instrumenting a state machine.
1. Pass the added automated tests
2. Manually tested deploying the stacks, with some other changes. See https://github.com/DataDog/datadog-cloudformation-macro/pull/143. I decided to break that PR into smaller ones for easy review, and this PR is the first one.
There are multiple ways for a user to specify a state machine …

[Step Function] 4. Add permissions to state machine role

---

serverless/src/lambda/forwarder.ts
serverless/src/step_function/env.ts
serverless/src/step_function/forwarder.ts
serverless/src/step_function/log.ts
serverless/src/step_function/step_function.ts
serverless/src/types.ts
serverless/test/step_function/forwarder.spec.ts
serverless/test/step_function/log.spec.ts

Subscribe the forwarder Lambda function to the state machine's log group, by creating a subscription filter.
This is one step of instrumenting a state machine.
1. Pass the added automated tests
2. Manually tested deploying the CloudFormation Macro stack then the app stack. A subscription filter is created:
The forwarder Lambda should be already created. We ask the user to specify it using the new `stepFunctionForwarderArn` field. I decided not to use …

[Step Function] 5. Add forwarder

---

serverless/src/common/tags.ts
serverless/src/lambda/env.ts
serverless/src/lambda/lambda.ts
serverless/src/lambda/layer.ts
serverless/src/lambda/tags.ts
serverless/test/lambda/tags.spec.ts

Most of the code for adding tags to a Lambda function can be reused for tagging a state machine. This PR refactors Lambda tagging code, so it's easier to reuse it for step functions.
Right now there are 4 functions for tagging a Lambda function:
```
function addDDTags(lambdas: LambdaFunction[], config: Configuration): void;
function addMacroTag(lambdas: LambdaFunction[], version: string | undefined): void;
function addCDKTag(lambdas: LambdaFunction[]): void;
function addSAMTag(lambdas: LambdaFunction[]): void;
```
`addDDTags()`, for example, takes `LambdaFunction` and Lambda's `LambdaFunction`, which not easily extensible to state machines.
This PR:
1. creates an interface `TaggableResource`, which is extended by `LambdaFunction` and will be extended by `StateMachine` in the next PR …

[Step Function] 6.2 Refactor Lambda tag code

---

serverless/src/step_function/env.ts
serverless/src/step_function/step_function.ts
serverless/src/step_function/tags.ts
serverless/src/step_function/types.ts
serverless/test/step_function/tags.spec.ts

Set tags on the state machine. For example, if the user specifies this configuration in the CloudFormation template:
```
Transform:
- Name: DatadogServerless
Parameters:
service: "my-service"
env: "dev"
version: "1.0.0"
tags: "tag-key1:tag-value1,tag-key2:tag-value2"
...
```
Then we will set these tags on the state machine:
```
service: "my-service"
env: "dev"
version: "1.0.0"
tag-key1: "tag-value1"
tag-key2: "tag-value2"
DD_TRACE_ENABLED: "true" …
```

[Step Function] 6.3 Set tags

---

serverless/src/step_function/span-link.ts
serverless/src/step_function/step_function.ts
serverless/src/step_function/types.ts
serverless/test/step_function/span-link.spec.ts

Adds skeleton code to prepare for setting up trace merging.
This PR assumes the state machine's definition is in this format:
```
Properties:
DefinitionString: !Sub | <JSON string>
```
However, there are many other ways to define the state machine's definition, e.g.
```
Properties:
DefinitionString: <JSON string>
```
```
Properties:
DefinitionString:
!Sub
- |-
<JSON string>
- <An object specifying …
```

[Step Function] 7.1 Add skeleton code for merging traces

---

serverless/src/step_function/span-link.ts
serverless/src/step_function/types.ts
serverless/test/step_function/span-link.spec.ts

There are many formats the state machine's `definitionString` field can take. See https://github.com/DataDog/datadog-cloudformation-macro/pull/158
Handles the case when the state machine's `definitionString` field is in this format:
```
Properties:
DefinitionString: <JSON string>
```
Trace merging is one step of instrumenting a state machine.

[Step Function] 7.2 Handle the case when definition is a string

---

serverless/src/step_function/span-link.ts
serverless/src/step_function/types.ts
serverless/test/step_function/span-link.spec.ts

There are many formats the state machine's `definitionString` field can take. See https://github.com/DataDog/datadog-cloudformation-macro/pull/158
Handles the case when the state machine's `definitionString` field is in this format:
```
Properties:
DefinitionString:
!Sub
- |-
<JSON string>
- <An object specifying substitutions> (optional)
```

[Step Function] 7.3 Handle definition is {"Fn::Sub": array}

---

serverless/src/step_function/span-link.ts
serverless/src/step_function/types.ts
serverless/test/step_function/span-link.spec.ts

There are many formats the state machine's `definitionString` field can take. See https://github.com/DataDog/datadog-cloudformation-macro/pull/158
Handles the case when the state machine's `definitionString` field is in this format:
```
Properties:
Definition: <an object>
```
It involves moving some commonly-used interfaces from `step_function/span-link.ts` to `step_function/types.ts`.

[Step Function] 7.6 Handle the case when definition is an object

---

serverless/src/step_function/forwarder.ts
serverless/src/step_function/log.ts
serverless/test/step_function/forwarder.spec.ts
serverless/test/step_function/log.spec.ts

When I deploy an application stack that includes a step function and uses our CloudFormation Macro, deployment fails when creating the log group subscription filter. It says the log group is not found.
Add a `DependsOn` field to specify that the subscription filter depends on the log group.
Deploy the CloudFormation Macro stack then the application stack. The application stack could deploy successfully. Both the log group and the subscription filter …

[Step Function] 8.1 Fix subscription filter creation failure

---

serverless/src/step_function/span-link.ts
serverless/src/step_function/types.ts
serverless/test/step_function/span-link.spec.ts

There are many formats the state machine's `definitionString` field can take. See https://github.com/DataDog/datadog-cloudformation-macro/pull/158
Handles the case when the state machine's `definitionString` field is in this format:
```
Properties:
DefinitionString:
Fn::Join:
- "\n"
- <JSON lines of definition>
```
This is what our CloudFormation Macro will get when the user uses resource type `AWS::Serverless::StateMachine` and use …

[Step Function] 7.7 Handle: definitionString uses Fn::Join

---

serverless/Dockerfile

This PR will slightly modify the Dockerfile so that it'll trigger the CI image to build in the gitlab pipeline. Here's the relevant PR for it: https://github.com/DataDog/serverless-ci/pull/3 and [comment](https://github.com/DataDog/serverless-ci/pull/3#discussion_r1965678216)

Change dockerfile to trigger ci image build in gitlab 

---

serverless/tools/generate_jwt.sh
serverless/tools/get_secrets.sh

Generate the GH token from an app key instead of using someone's PAT.
* JIRA: https://datadoghq.atlassian.net/browse/SVLS-6933
* I tried it out in [gitlab](https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/981892383#L59) with an extra API call.  Note this isn't doing the release but a different call I added
* I'll try out the CFN macro release after this is merged

Generate GH token instead of using PAT

---

serverless/package.json
serverless/release.sh
serverless/test/lambda/env.spec.ts
serverless/yarn.lock

Add the types/jest module in the package.json as a dev dependency instead of just adding it as a dev dependency during the release. The build failed in the release process because of this toThrowError vs toThrow, this should move those failures to development time instead of when we go to release.
Error:https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/983337668#L124
Unblock the release process
Automated checks in this PR should be sufficient

Add types/jest in package, not release

---

serverless/release.sh

Tests running in gitlab fail, I'm not sure why.  It seems like a test isolation thing based on the error, but we didn't run tests before so I'm reverting the change back to not running the tests with a comment of why so I can get the release out for AP2
Failed run: https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/983419016
Unblock the release process
I ran it in gitlab this time, not on my local.  It even works - https://gitlab.ddbuild.io/DataDog/datadog-cloudformation-macro/-/jobs/983456169

Don't run test in release script
